### ISSUE TITLE
How attachment files?

### ISSUE THREAD

**Issue by SHKEd** [snipworks/php-smtp#6]
How attachment files?

**Comment by snipworks** [comment]
Unfortunately, file attachments are not supported since the current code handles html and plain text multipart boundaries. You can modify the code to handle boundaries for attachments.

You may refer to this example: https://stackoverflow.com/questions/690430/attnnnnn-txt-attachments-when-e-mail-is-received-in-outlook

**Comment by snipworks** [comment]
I've already added mixed boundaries to handle attachments in version `2.0.0`. See examples directory for the usage.
